CONTROLLER_BASE_MESSAGE = "controller."
ARDUINO_BASE_MESSAGE = "arduino."
FRONTEND_BASE_MESSAGE = "frontend."

CONTROLLER_STATE_MESSAGE = CONTROLLER_BASE_MESSAGE + "state"
MICROCONTROLLER_MESSAGE = "microcontroller"