CONTROLLER_BASE_MESSAGE = "controller."
ARDUINO_BASE_MESSAGE = "arduino."
FRONTEND_BASE_MESSAGE = "frontend."

CONTROLLER_STATE_MESSAGE = "CONTROLLER_STATE_MESSAGE"
RECIEVED_MESSAGE_FROM_MICROCONTROLLER = "RECIEVED_MESSAGE_FROM_MICROCONTROLLER"
RECIEVED_ACK_MESSAGE_FROM_MICROCONTROLLER = "RECIEVED_ACK_MESSAGE_FROM_MICROCONTROLLER"
SEND_MESSAGE_TO_MICROCONTROLLER = "SEND_MESSAGE_TO_MICROCONTROLLER"
SEND_MESSAGE_TO_FRONTEND = "SEND_MESSAGE_TO_FRONTEND"
RECIEVED_MESSAGE_FROM_FRONTED = "RECIEVED_MESSAGE_FROM_FRONTED"

